chat/chat/apps/profile/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
	"chat.apps.profile.views",

	url(r"^profile/edit/$", "edit_profile", name="edit_profile"),
)

chat/chat/urls.py
from django.conf.urls import patterns, include, url
from chat.apps.account.views import LoginView, SignupView, logout

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'chat.views.home', name='home'),
    # url(r'^chat/', include('chat.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    url(r"^account/login/$", LoginView.as_view(), name="account_login"),
    url(r"^account/signup/$", SignupView.as_view(), name="account_signup"),
    url(r"logout/$", logout, name="account_logout"),

    url(r"^people/", include("chat.apps.profile.urls")),
    url(r"^people/", include("chat.apps.friend.urls")),
    url(r"^messages/", include("chat.apps.message.urls")),

    url(r"^account/", include("account.urls")),
    url(r'^avatar/', include('avatar.urls')),
    url(r"^", include("chat.apps.dashboard.urls")),
    
)

chat/chat/apps/profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from django.db.models.signals import post_save


class Gender:
    MALE = 1
    FEMALE = 2

GENDER_CHOICES = (
    (Gender.MALE, "Male"),
    (Gender.FEMALE, "Female")
)


class Profile(models.Model):

    class Meta:
        app_label = "profile"

    user = models.OneToOneField(User, unique=True, verbose_name="user", related_name="profile")
    full_name = models.CharField( _("Full Name"), max_length=30, null=True, blank=True)
    gender = models.SmallIntegerField(choices=GENDER_CHOICES, default=Gender.MALE)
    location = models.CharField(max_length=50, null=True, blank=True)
    country = CountryField(null=True, blank=True)
    about = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.full_name


def create_profile_for_new_user(sender, instance=None, **kwargs):
    if instance is None:
        return

    profile, created = Profile.objects.get_or_create(user=instance)
    if created:
        profile.full_name = "%s %s" % (instance.first_name, instance.last_name)
        profile.save()

post_save.connect(create_profile_for_new_user, sender=User)

chat/chat/apps/profile/forms.py
from django import forms
from chat.apps.profile.models import Profile


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ["full_name", "gender", "location", "country", "about"]

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields["full_name"].required = True

    def clean_full_name(self):
        full_name = self.cleaned_data.get('full_name').strip()
        if not full_name:
            return forms.ValidationError("This field is required.")
        return full_name

chat/chat/apps/profile/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from chat.apps.profile.forms import ProfileForm


@login_required
def edit_profile(request):
    if request.POST:
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, _("Profile updated."))
    else:
        form = ProfileForm(instance=request.user.profile)

    return render(request, "profile/edit_profile.html", {'form': form})

chat/chat/apps/profile/templates/profile/edit_profile.html
{% extends "dashboard/base.html" %}


{% block extra_static_files %}

    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-fileupload.min.css" type="text/css" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-migrate-1.1.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.10.3.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-fileupload.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-timepicker.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.uniform.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.tagsinput.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.autogrow-textarea.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/charCount.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/colorpicker.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/ui.spinner.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/chosen.jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.cookie.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/modernizr.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.slimscroll.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/custom.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/forms.js"></script>
{% endblock %}

{% block page_header %}
    <div class="pageicon"><span class="iconfa-laptop"></span></div>
    <div class="pagetitle">
        <h1>Edit Profile</h1>
    </div>
{% endblock page_header %}
        
{% block main_content %}
    <div class="maincontentinner">
        <div class="row-fluid">
            <div class="span8">
                <form action="{{ request.path }}" class="editprofileform" method="post">
                    {% csrf_token %}
                    <div class="widgetbox personal-information">
                        <h4 class="widgettitle">Personal Information</h4>
                        <div class="widgetcontent">
                            
                            <div class="par">
                                <label for="inputError" class="control-label">Full Name</label>
                                <div class="controls control-group {% if form.full_name.errors %} error {% endif %}">
                                    <input type="text" class="span4" name="full_name" id="id_full_name" placeholder="Full name" value="{{ form.full_name.value|default_if_none:'' }}">
                                    {% if form.full_name.errors %}
                                    <span class="help-inline">Please correct the error</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="par">
                                <label>Gender</label>
                                <span class="field">
                                    <select name="gender" id="id_gender" class="uniformselect span4">
                                        {% for choice in form.gender.field.choices %}
                                        <option value="{{ choice.0 }}" {% if form.gender.value = choice.0 %} selected {% endif %}>{{ choice.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </span>
                            </div>
                            <div class="par">
                                <label for="inputError" class="control-label">Location</label>
                                <div class="controls control-group {% if form.location.errors %}error{% endif %}">
                                    <input type="text" class="span4" name="location" id="id_location" placeholder="Location" value="{{ form.location.value|default_if_none:'' }}">
                                    {% if form.location.errors %}
                                    <span class="help-inline">Please correct the error</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="par">
                                <label>Country</label>
                                <span class="field control-group {% if form.country.errors %}error{% endif %}">
                                    <select name="country" id="id_country" class="uniformselect span4">
                                        {% for country in form.country.field.choices %}
                                        <option value="{{ country.0 }}" {% if form.country.value = country.0 %}selected{% endif %}>{{ country.1 }}</option>
                                        {% endfor %}
                                    </select>
                                    {% if form.country.errors %}
                                    <span class="help-inline">Please correct the error</span>
                                    {% endif %}
                                </span>
                            </div>
                            
                            <p>
                                <label>About You:</label>
                                <textarea name="about" id="id_about" class="span8" rows="10">{{ form.about.value|default_if_none:'' }}</textarea>
                            </p>
                        </div>
                    </div>
                                
                    <p>
                        <button type="submit" class="btn btn-primary">Update Profile</button> 
                    </p>
                                
                </form>
            </div><!--span12-->
        </div><!--row-fluid-->
                    
        <div class="footer">
            <div class="footer-left">
                <span>&copy; 2013. Shamcey Admin Template. All Rights Reserved.</span>
            </div>
            <div class="footer-right">
                <span>Designed by: <a href="http://themepixels.com/">ThemePixels</a></span>
            </div>
        </div><!--footer-->
                
    </div><!--maincontentinner-->
{% endblock main_content %}